<a href="https://colab.research.google.com/github/shonnvs-code/Team4-A1-BA820-Project/blob/main/Shon_Shaju_ProjectM2_Q2_BA820_Team_4_Childcare_Costs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Childcare Costs Dataset**

# **1. Executive Summary**

# **2.Question under analysis**

Q2.How do U.S. counties cluster into distinct childcare market types based on pricing structure and affordability pressure, and how do these market types differ in maternal labor force participation? Specifically, do clusters exist where maternal labor participation remains high despite extreme childcare cost-to-income ratios, or where participation remains low even at moderate cost levels?

# **3.Loading Data**

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [ ]:
# If you uploaded both files to Colab, this will work:
childcare_path = "childcare_costs.csv"
counties_path  = "counties.csv"

cc = pd.read_csv(childcare_path)
ct = pd.read_csv(counties_path)

print("childcare_costs:", cc.shape)
print("counties:", ct.shape)

cc.head()

In [9]:
childcare = pd.read_csv('/content/drive/MyDrive/childcare_costs.csv')
counties  = pd.read_csv('/content/drive/MyDrive/counties.csv')

print("childcare shape:", childcare.shape)
print("counties shape:", counties.shape)
childcare.head()

childcare shape: (34567, 61)
counties shape: (3144, 4)

,county_fips_code,study_year,unr_16,funr_16,munr_16,unr_20to64,funr_20to64,munr_20to64,flfpr_20to64,flfpr_20to64_under6,...,memp_p,femp_p,mcsa,mfccsa,mc_infant,mc_toddler,mc_preschool,mfcc_infant,mfcc_toddler,mfcc_preschool
0,1001,2008,5.42,4.41,6.32,4.6,3.5,5.6,68.9,66.9,...,21.55,4.07,80.92,81.40,104.95,104.95,85.92,83.45,83.45,81.40
1,1001,2009,5.93,5.72,6.11,4.8,4.6,5.0,70.8,63.7,...,21.96,5.19,83.42,85.68,105.11,105.11,87.59,87.39,87.39,85.68
2,1001,2010,6.21,5.57,6.78,5.1,4.6,5.6,71.3,67.0,...,21.28,4.13,85.92,89.96,105.28,105.28,89.26,91.33,91.33,89.96
3,1001,2011,7.55,8.13,7.03,6.2,6.3,6.1,70.2,66.5,...,22.80,4.77,88.43,94.25,105.45,105.45,90.93,95.28,95.28,94.25
4,1001,2012,8.60,8.88,8.29,6.7,6.4,7.0,70.6,67.1,...,22.88,4.84,90.93,98.53,105.61,105.61,92.60,99.22,99.22,98.53

In [10]:
# mereging both the data sets
df = childcare.merge(counties, on="county_fips_code", how="left")
df

,county_fips_code,study_year,unr_16,funr_16,munr_16,unr_20to64,funr_20to64,munr_20to64,flfpr_20to64,flfpr_20to64_under6,...,mfccsa,mc_infant,mc_toddler,mc_preschool,mfcc_infant,mfcc_toddler,mfcc_preschool,county_name,state_name,state_abbreviation
0,1001,2008,5.42,4.41,6.32,4.6,3.5,5.6,68.9,66.9,...,81.40,104.95,104.95,85.92,83.45,83.45,81.40,Autauga County,Alabama,AL
1,1001,2009,5.93,5.72,6.11,4.8,4.6,5.0,70.8,63.7,...,85.68,105.11,105.11,87.59,87.39,87.39,85.68,Autauga County,Alabama,AL
2,1001,2010,6.21,5.57,6.78,5.1,4.6,5.6,71.3,67.0,...,89.96,105.28,105.28,89.26,91.33,91.33,89.96,Autauga County,Alabama,AL
3,1001,2011,7.55,8.13,7.03,6.2,6.3,6.1,70.2,66.5,...,94.25,105.45,105.45,90.93,95.28,95.28,94.25,Autauga County,Alabama,AL
4,1001,2012,8.60,8.88,8.29,6.7,6.4,7.0,70.6,67.1,...,98.53,105.61,105.61,92.60,99.22,99.22,98.53,Autauga County,Alabama,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34562,56045,2014,3.60,5.36,2.28,2.4,4.8,0.6,75.9,74.8,...,112.94,147.36,120.38,123.99,110.71,110.71,111.47,Weston County,Wyoming,WY
34563,56045,2015,5.16,7.86,3.16,4.2,7.6,1.6,73.2,82.0,...,110.89,140.36,118.77,118.77,110.89,110.89,110.89,Weston County,Wyoming,WY
34564,56045,2016,3.61,4.67,2.79,3.4,4.5,2.6,69.7,68.1,...,108.85,133.37,117.16,113.55,114.10,111.07,110.31,Weston County,Wyoming,WY
34565,56045,2017,2.24,2.64,1.95,2.3,2.8,2.0,71.4,63.6,...,106.81,126.38,115.55,108.32,117.30,111.26,109.74,Weston County,Wyoming,WY
34566,56045,2018,3.54,2.86,4.04,3.7,2.8,4.4,67.7,57.8,...,104.76,126.18,113.93,103.10,120.50,111.44,109.16,Weston County,Wyoming,WY

# **4.EDA**